### ISSUE TITLE
No documented way of creating new sub-project

### ISSUE THREAD

**Issue by raiju** [palantir/gradle-revapi#110]
## What happened?

When creating a new subproject in an existing project with revapi enabled, revapi errors out with no apparent way of marking the break through the config interface (it always fails with a "Failed to resolve old API"-type error).

The errors in the template take the pattern of:

```
  We tried version $latest but it failed with errors:
  Could not find $project:$pkg:$latest.
  Searched in the following locations:
    - ...
    - ...

...
```

## What did you want to happen?

Either a command to tell revapi that a project was just added, or a way to get the `revapiAcceptAllBreaks` command to work in those circumstances. If there already exists a way to handle this, we should document it in the readme.

**Comment by CRogers** [comment]
I think you can avoid adding revapi to that project until it has a release to unblock?

A more long term option could be to see if there are *any* releases for that version (resolving a `+` dependency to do this?) and then if there are no releases at all skip. Or see if the project dir existed in git at the previous tag and if not skip the tag.
