### ISSUE TITLE
revapi.yml output should alphabetical

### ISSUE THREAD

**Issue by topherinternational** [palantir/gradle-revapi#115]
It appears that both `versionOverrides` and `acceptedBreaks` render in a non-alphabetical order (and out of order with each other) when listing artifact/project keys in `revapi.yml`. This makes reviewing break listings in PRs, as well as reading the breaks post-facto, less predictable that it could be, and difficult to correlate across multiple versions' changes.

## What happened?
Example `revapi.yml` in a recent PR after accepting changes (names notionalized but otherwise order is maintained):

```
versionOverrides:
  com.company.module:myproject-examples:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-api:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-runtime-module:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:binary-format:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-impl:1.100.0: "1.101.0-7-gabcdef0"
acceptedBreaks:
  "1.110.0":
    com.company.module:myproject-examples: []
    com.company.module:binary-format: []
    com.company.module:myproject-api:
    - code: "java.method.addedToInterface"
      ...
...
```

## What did you want to happen?
It would be lexically natural and more review-friendly if the output was more like this:
```
versionOverrides:
  com.company.module:binary-format:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-api:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-examples:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-impl:1.100.0: "1.101.0-7-gabcdef0"
  com.company.module:myproject-runtime-module:1.100.0: "1.101.0-7-gabcdef0"
acceptedBreaks:
  "1.110.0":
    com.company.module:binary-format: []
    com.company.module:myproject-api:
    - code: "java.method.addedToInterface"
      ...
    com.company.module:myproject-examples: []
...
```

**Comment by CRogers** [comment]
+suggestion from @iamdanfox to group the breaks by `old` class so it makes it easier to go through the breaks one by one.

I would also like to hike up the `justification` to a higher level so there's less duplication and the new breaks are all grouped together. Also rename the misleading `version` to `after-version` or similar as the breaks didn't actually occur in that version. I had a half baked PR to do these at [this branch](https://github.com/palantir/gradle-revapi/compare/fix-semantic-merge-conflicts#diff-659ae9178c68c5dbb699fcc24a089aa1R214-R223).
