### ISSUE TITLE
Automatically strip leading "v" from version tags

### ISSUE THREAD

**Issue by Clashsoft** [palantir/gradle-revapi#145]
## What happened?

The plugin failed to resolve the old version of our project because we use tags in the format `vX.X.X`, while maven coordinates usually use `X.X.X`.

## What did you want to happen?

Tags should be normalized by stripping the leading "v".

**Comment by CRogers** [comment]
@Clashsoft Just released 1.1.3 which should fix this - thanks for the report!

**Comment by Clashsoft** [comment]
@CRogers Wow that was fast! Thanks a lot!
