### ISSUE TITLE
Incompatible with Gradle v7

### ISSUE THREAD

**Issue by Clashsoft** [palantir/gradle-revapi#439]
## What happened?

Using the plugin with Gradle v7(.0.2) generates this error:

```
A problem was found with the configuration of task ':revapiAnalyze' (type 'RevapiAnalyzeTask').
  - Type 'com.palantir.gradle.revapi.RevapiAnalyzeTask' property 'analysisResultsFile' is annotated with @PathSensitive but that is not allowed for 'OutputFile' properties.
    
    Reason: This modifier is used in conjunction with a property of type 'OutputFile' but this doesn't have semantics.
    
    Possible solution: Remove the '@PathSensitive' annotation.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#incompatible_annotations for more details about this problem.
```

## What did you want to happen?

The plugin should be compatible with Gradle v7 and no error should occur.

**Comment by ash211** [comment]
I'm using this plugin with Gradle 7.6.2 and have seen no issues.  @Clashsoft did this work for you with a later Gradle version?  

I don't see a changelog at https://github.com/palantir/gradle-revapi/releases mentioning Gradle 7 compatibility, so I'm not sure if something relevant changed in Gradle or in this plugin.

**Comment by Clashsoft** [comment]
Maybe it was updated and the underlying problem fixed. I dont use it anymore
