### ISSUE TITLE
False positive when moving a class from one package to dependent package

### ISSUE THREAD

**Issue by CRogers** [palantir/gradle-revapi#60]
## What happened?

If you move class `Foo` from project `core` to project `dependency`, where `core` depends on `dependency` as `api`, then revapi will create a spurious error saying it's a breaking change, even though the class is still on the classpath when using `core`.

## What did you want to happen?

Revapi should not create an error in this case.

**Comment by metlos** [comment]
This is basically the opposite of https://github.com/palantir/gradle-revapi/issues/75 :smile:
